# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c8e1b994af3b32d117776d58184fd08321fefcdc92a6960a0cd29e51a776293aa8f70eb2df78bbbcbd004badb9cdef94b1050b4a6a0174eb795e778f3117c389

test:
  secret_key_base: d4ff5b0b0dbc7755a382b7d959a2e4223500a7df39ed3de6c360e0c1525662c6c1acf0946c6eb4e248f317d6d6d8183559697b8992ef73e69e0d99fa86d0af88

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
